### ISSUE TITLE
V4 Roadmap

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-javascript#195]
Here are some V4 goals I would like to tackle:
- [ ] switch codebase to ES6
- [ ] allow building modular clients (search only, places). Mostly by extracting the requester into a single object
- [ ] switch to webpack
- [ ] automatic releases through npm and jsdelivr
- [ ] monorepo architecture with packages/algoliasearch-[jquery|angular..]
- [ ] publish packages/ so that they can be required easily
- [ ] experiment with rollup (seems to be the promising ES6 focused module builder, low overhead)
- [ ] automatic changelog
- [ ] drop non-CORS browsers
- [ ] drop non ES5 browsers
- [ ] provide a search only client through a specific package
- [ ] provide a specific places client through a specific package
- [ ] stop building complex stateful prototype based objects, use simple wrappers
- [ ] do real unit testing, drop the testing stack
- [ ] use mocha, jsdom
- [ ] default to https for write actions, browser protocol for reads
- [ ] review API #204 
- [ ] remove all legacy signatures and already deprecated methods in V3
- [ ] provide a compatibility layer package to ease the migration, with clear messages on what to change
- [ ] generateSecuredAPIKey should be static (maybe other methods)
- [ ] clearly identify public/private props
- [ ] requests should be cancelable
- [ ] drop callback support, promises only, show how to still use callbacks
- [ ] bootstrap website
- [ ] full jsdoc (see https://esdoc.org/) on website
- [ ] single cache, no more client AND index cache
- [ ] run unit tests with karma (maybe)
- [ ] code coverage and automation
- [ ] use greenkeeper.io
- [ ] monitor V3 /latest usage before publishing
- [ ] drop jsdelivr /latest compatibility layer (we automatically load V2 when used with /latest/ on jsdelivr)
- [ ] drop shrinkwrap
- [x] introduce read and write timeouts
- [ ] library should work in service workers
- [ ] client instantiation should be an option object even for apiKey and appId, this is already the case of instantsearch.js for example. Or docsearch
- [ ] add a .preconnect method on client that will initiate the connection (use case: click in input)

**Comment by kievechua** [comment]
Hi @vvo, when can we expect generateSecuredApiKey implemented?
This issue been for more than a year.
Also didn't see any rest api I can implement it.
Can you point me to correct direction?

**Comment by Haroenv** [comment]
You should be able to do `client.generateSecuredApiKey()` on your instance already @kievechua

**Comment by kievechua** [comment]
Sorry, got confused with this line.
https://github.com/algolia/algoliasearch-client-javascript/blob/master/src/AlgoliaSearch.js#L485

@Haroenv Another issue is there anyway to update or delete the securedApiKey?

**Comment by vvo** [comment]
@kievechua Please open a new issue describing your problem, thanks!

**Comment by Haroenv** [comment]
This can be summarised in this roadmap: 


- Reduce the methods of the API clients:
  - deprecated
  - deprecate singular

- Future-first
  - only Promises
  - no Polyfills
  - evergreen browser support
    - CORS stuff

- Make it easier to iterate
  - build process
  - release process
  - unit testing

- exporting single methods
  - `import { search } from 'algolia'`
  - also add initIndex

- publish builds separately
  - jquery
  - angular
  - react-native --> no different package
  - parse --> maybe no different package
  - service workers --> does it work?

- rethink request strategy
  - less complexity
  - no fallbacks
  - _jsonRequest is the complex function
  - use fetch first #561

**Comment by vvo** [comment]
awesome action plan! looking forward to it :)

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we toke in consideration all those points.
